apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: przemek.malak@gmail.com # me@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01: 
          ingress:
            class: nginx
        selector: {}